apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-unbloat-k8s.fullname" . }}
  labels:
    {{- include "postgres-unbloat-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-unbloat-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-unbloat-k8s.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-unbloat-k8s.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (print "v" .Chart.AppVersion) }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --mode=in-cluster
          - --dry-run={{ .Values.config.dryRun }}
          - --namespace={{ .Values.config.kubernetes.namespace | default .Release.Namespace }}
          - --log-level={{ .Values.config.logging.level | default "info" }}
          - --webhook-port={{ .Values.config.webhook.port | default 8080 }}
          - --webhook-path={{ .Values.config.webhook.path | default "/webhook" }}
        ports:
          - name: webhook
            containerPort: {{ .Values.config.webhook.port | default 8080 }}
            protocol: TCP
          - name: metrics
            containerPort: {{ .Values.server.metricsPort | default 9090 }}
            protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
